version: '2'

# Named volumes
volumes:

  # MySQL Data
  blog-mysql-data:
    driver: local

  # Redis Data
  blog-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: blog-mysql
    volumes:
      - blog-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=blog
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=blog

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: blog-redis
    command: --appendonly yes
    volumes:
      - blog-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: blog-app
    volumes:
      - .:/var/www/app
    ports:
      - "443:443"
    links:
      - mysql
      - cache